
<div class="menu_order">
    <ul>
    <li><a href="http://www.netakart.com/index.php/salesreport/order">Dashboards</a></li>
    <li><a href="http://www.netakart.com/index.php/salesreport/margins">Sales & Margin</a></li>
    <li><a href="">COD Remit</a></li>
    <li><a href="">Payments to Vendor</a></li>
    <li><a href="">Vendor Performance</a></li>
    <li><a href="">Logistics Performance</a></li>
    </ul>
</div>
