<?php $_helper = $this->helper('supplier'); ?>
<tr>
    <td>
    	<h2 class="content-heading"><?php echo $_helper->__('Ultimate Dropship');?> <?php echo Mage::getConfig()->getModuleConfig("Magentomasters_Supplier")->version;?></h2>
    </td>
</tr>
<tr>
	<td>
    	<a href="mailto:support@magextended.com">support@magextended.com</a><br/>
    	<a href="http://www.magextended.com" target="_blank">http://www.magextended.com</a>
    </td>
</tr>