<?php	 $orders = $this->getOrders();
		 echo $this->getChildHtml("order_list_toolbar"); ?>
<?php //$status =  $this->getOrderStatus();

$status = $this->getCustomStatus();
$session = Mage::getSingleton('core/session');
$salesId = $session->getData('salesId');
$orderStatus = array('paypal_canceled_reversal','payment_review', 'paypal_reversed','pending_payment', 'pending_paypal','fraud','closed','pending','processing','ready_for_dispatch','canceled','holded');
?>

<?php if(!isset($_GET['s'])){ ?>
<div class="supllier_admin_content  supplier_admin_order_list">
<h1>Order Summary</h1>
<table class="supplier_order_list st" style="width:100%" >
	    <tr class="menu_font_style " id="padd">
	        <th><?php echo $this->__('Index') ?></th>
	        <th><?php echo $this->__('Orders') ?></th>
	        <th><?php echo $this->__('Value') ?></th>
	        <!--<th><?php echo $this->__('Status') ?></th>-->
	        <th><?php echo $this->__('Details') ?></th>
	    </tr>
	    <?php $i = 0;
		$priceTotal = 0;
		 foreach($status as $order) : $i++; ?>
        	
            <?php switch($order['status']){
			case 'processing':
			$customStatus = 1;
			break;	
			case 'ready_for_dispatch':
			$customStatus = 2;
			break;	
			case 'readypickup':
			$customStatus = 3;
			break;	
			case 'handed_courier':
			$customStatus = 4;
			break;	
			case 'complete':
			$customStatus = 5;
			break;
			case 'canceled':
			$customStatus = 6;
			break;
			case 'holded':
			$customStatus = 7;
			break;		
		
	}
		?>
        
        <?php $countStatus = $this->getOrderByStatus($courierId, $order['status']); ?>
         <?php if(!in_array($order['status'],$orderStatus)){
			 $priceTotal = $countStatus['price'];
			 ?>
	    <tr class="position  <?php if(($i%2) == 0){?>even<?php }else{?>odd<?php } ?>"> 
	        <td><?php echo $order['label']; ?></td>
	        <td><?php 
					if($countStatus['countOrder'] > 0){
					echo $countStatus['countOrder'];
					}
					else {
					echo 0;
					}
			
			 ?></td>
	        <td>Rs. <?php echo number_format($priceTotal); ?></td>
	        <td><a href="<?php echo Mage::getUrl('courier/order/' ).'?s='. $customStatus; ?>"><?php echo $this->__('View') ?></a></td>
	    </tr>
        <?php } ?>
	    <?php endforeach; ?>
	</table>


</div>
<?php } else { 
			$cstatus = Mage::app()->getRequest()->getParam('s');
			switch($cstatus){
				case '1':
				$customStatus = 2;
				$buttonLabel = 'Change Status to Ready for Dispatch';
				$statusO = 'ready_for_dispatch';
				break;	
				case '2':
				$customStatus = 3;
				$buttonLabel = 'Change Status to Ready for Pickup';
				$statusO = 'readypickup';
				break;	
				case '3':
				$customStatus = 4;
				$buttonLabel = 'Change Status to Handed to Courier';
				$statusO = 'handed_courier';
				break;	
				case '4':
				$customStatus = 5;
				$buttonLabel = 'Change Status to Delivered';
				$statusO = 'complete';
				break;	
				case '5':
				$customStatus = 5;
				break;
				default:
				$customStatus = 0;
				$buttonLabel = '';
			}
?>
<h1>Order Acception</h1>

<div class="supllier_admin_content  supplier_admin_order_list">
<form name="order-status" id="order-status" action="" method="post">
	<table class="supplier_order_list st" style="width:100%" >
	    <tr class="menu_font_style " id="padd">
	        <th><?php echo $this->__('Order ID') ?></th>
            <th><?php echo $this->__('OrderType') ?></th>
            <th><?php echo $this->__('AwbNo') ?></th>
            <th><?php echo $this->__('Courier Partner') ?></th>
            <th><?php echo $this->__('Supplier') ?></th>
            <th><?php echo $this->__('Supplier Address'); ?></th>
              <th><?php echo $this->__('SKUCode') ?></th>
               <th><?php echo $this->__('Product Name') ?></th>
               <th><?php echo $this->__('Customer Details') ?></th>
	        <th><?php echo $this->__('OrderDate') ?></th>
            <th><?php echo $this->__('Qty') ?></th>
            <th><?php echo $this->__('Total Amt') ?></th>
	       
	    </tr>
	    <?php $i = 0; foreach($orders as $order) :  ?>
        
        <?php
			$orderPayment = new Mage_Sales_Model_Order();
			$orderPayment->loadByIncrementId($order['order_number']);
			$payment_method = $orderPayment->getPayment()->getMethodInstance()->getTitle();
			$supplierDetails = $this->getSupplierInfo($order['supplier_id']);
			
			
			$order1 = Mage::getModel("sales/order")->load($order['order_id']); //load order by order id 
			$billing_address = $order1->getBillingAddress(); 
			
			//print_r($billing_address);	
							
			if($order['courier_id']==1){
				$courier = 'Red Express';
			} else {
				$courier = 'Delhivery';
			}
		?>
        <?php $sku = $this->getCustomSku($order['order_number']); ?>
	    <tr class="position  <?php if(($i%2) == 0){ ?> even <?php } else { ?>odd<?php } ?>"> 
	        <td><a href="<?php echo Mage::getUrl('courier/order/view/' ) . 'order_id/' . $order['order_id']; ?>"><?php echo $order['order_number']; ?></a></td>
            <td><?php echo $payment_method; ?></td>
            <td><?php echo $order['awbno']; ?></td>
            
            <td><?php echo $courier; ?></td>
            
            <td><?php echo $supplierDetails['company']; ?></td>
            <td><?php echo $supplierDetails['address1']."<br>".$supplierDetails['city']."<br>".$supplierDetails['state']."<br>".$supplierDetails['postalcode']."<br>".$supplierDetails['Country']."<br> Phone - ".$supplierDetails['phone']; ?></td>
            <td><?php echo $sku['sku']; ?></td>
            <td><?php echo $sku['product_name']; ?></td>
            <td><?php echo $billing_address->getName()."<br>".$billing_address->getData('street')."<br>".$billing_address->getData('city')."<br>".$billing_address->getData('state')."<br>".$billing_address->getData('country')."<br>".$billing_address->getTelephone()."<br>".$billing_address->getPostcode(); ?></td>
            <td><?php echo Mage::helper('core')->formatDate($order['date'], 'short', $showTime=true); ?></td>
            <td><?php echo $sku['qty']; ?></td>
            <td><?php echo number_format($sku['price']); ?></td>
            
	    </tr>
	    <?php $i++; 
		endforeach; ?>
        
	</table>
    </form>
</div>
<?php } ?>
