<h2 class="txt-heading">Upload Your Resume</h2>
<div class="info-user">
<ul class="form-user-info">
<li><label>First Name</label> <input type="text" name="name" /></li>
<li><label>Last Name</label> <input type="text" name="last-name" /></li>
<li><label>E-mail</label> <input type="text" name="email" /></li>
<li><label>Mobile</label> <input type="text" name="mobile" /></li>
<li><label>Upload Your Resume</label> <input type="file" /></li>
<li><label>&nbsp;</label> <button class="button" type="button"><span><span>UPLOAD</span></span></button></li>
</ul>
</div>
