<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
 $footer_status = $meigee_blacknwhite_general['footer']['footer_status'];
 $footer_static = $meigee_blacknwhite_general['footer']['footer_static'];
?>


<footer id="footer"<?php if ($footer_status == 0): ?> class="default-footer"<?php endif; ?>>
	<?php if ($footer_status == 1): ?>
		 <?php echo $this->getChildHtml($footer_static); ?>
	<?php else: ?>
		<div class="footer-bottom-wrapper">
			<div class="container_12">
				<?php echo $this->getChildHtml('footer.newsletter'); ?>
				<div class="grid_12">
					<address><?php echo $this->getCopyright(); ?></address>
					<?php echo $this->getChildHtml('store_switcher'); ?>
					<?php echo $this->getChildHtml('store_language'); ?>
					<?php echo $this->getChildHtml('currency'); ?>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	<?php endif; ?>
</footer>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>