<head>
<style type = "text/css">
body{ font-size: 18px; }
h1 { font-size: 32px; }
h2 { font-size: 28px; }
td { margin: 0; padding: 0; }
tr {margin: 0; padding: 0;}
</style>
</head>
<body>
<div>
<?php
//$params = $pdf->serializeTCPDFtagParameters(array('40144399300102444888207482244309', 'C128C', '', '', 0, 0, 0.2, array('position'=>'S', 'border'=>false, 'padding'=>4, 'fgcolor'=>array(0,0,0), 'bgcolor'=>array(255,255,255), 'text'=>false, 'font'=>'helvetica', 'fontsize'=>8, 'stretchtext'=>2), 'N')); 
		
?>
<!--{{var barcode}}-->
<table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-top:-100px;">
	<tr><td colspan="2">AWB# {{var barcode}}</td></tr>
	<tr style="margin:0px; padding:0px;"><td colspan="2" align="center">{{var logo_pdf}}</td></tr>
    <tr><td colspan="2"><hr></td></tr>
	<tr>
    	 <td colspan="2">
              	<h2>{{var surname}},</h2>{{var saddress}}, {{var city}}, {{var state}}, {{var postalcode}}, {{var country}}
         
        </td>
	</tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td><table width="100%" border = "1" cellspacing="0" cellpadding="4">
        		<tr bgcolor="#CCCCCC"><td colspan="2"><h2>Order info</h2></td></tr>
                <tr><td><strong>Order number</strong></td><td>{{var order.increment_id}}</td></tr>
				<tr><td><strong>Order date</strong></td><td>{{var order.getCreatedAtFormated('short')}}</td></tr>
				<tr><td><strong>Order released date</strong></td><td>{{var dropship_date}}</td></tr>
                <tr><td><strong>TIN</strong></td><td>{{var tin}}</td></tr>
                <tr><td><strong>Service Tax #</strong></td><td>{{var servicetax}}</td></tr>
        	</table></td>
    	<td>
        		<table width="100%" border = "1" cellspacing="0" cellpadding="4">
                <tr><td><font size="10">Payment Mode</font></td><td><font size="10"><b>{{var payment_method}}</b></font></td></tr>
                <tr><td><font size="10">Courier</font></td><td><font size="10"><b>Delhivery</b></font></td></tr>
                </table>   
                
                    	
        </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td>
        	<table width="100%" border = "1" cellspacing="0" cellpadding="4">
				<tr bgcolor="#CCCCCC">
                	<td><h2>Billing address</h2></td>
                </tr>
                <tr>    
                	<td>{{var order.getBillingAddress().format('html')}}</td>
                </tr>
			</table>	
		</td>
        <td>
        	<table width="100%" border = "1" cellspacing="0" cellpadding="4">
				<tr bgcolor="#CCCCCC">
                	<td><h2>Shipping address</h2></td>
                </tr>
                <tr>    
                	<td>{{var order.getShippingAddress().format('html')}}</td>
                </tr>
			</table>
        </td>
	</tr>
    <tr>
    	<td>
	    	<table>
	        	<tr>
	            	<td>
	                    <h1>{{var pdf_header}}</h1>
	                    <p>{{var pdf_message}}</p>
	            	</td>
	            </tr>
	            <tr>
	            	<td>
	                	<br/><br/><h2>Ordered items</h2><br/>
	                </td> 
	            </tr>
	        </table>
        </td>
    </tr>
    <tr>
    	<td colspan="2">
        	<table width="100%" border = "1" cellspacing="0" cellpadding="4">
                <tr bgcolor="#CCCCCC">
                    <td width="250">Product Name</td>
                    <td>Details</td>
                    <td width="50">SKU</td>
                    <td width="50">Size</td>
                    <td width="50">Quantity</td>
                    <td width="50">Price</td>
                </tr>
                {{var pdf_items}}
                <tr><td colspan="5" align="right">Subtotal:</td><td align="right">{{var sub_total_cost}}</td></tr>
                <tr><td colspan="5" align="right">Shipping Amount:</td><td align="right">{{var discount}}</td></tr>
                <tr><td colspan="5" align="right">Total Amount:</td><td align="right">{{var total_cost}}</td></tr>
            </table>
        </td>
    </tr> 
    <tr><td colspan="2" align="right"><i>Inclusive all taxes</i></td></tr>
    <tr><td colspan="2"><br><br><br><br><br><br><br><br><br><br>&nbsp;</td></tr>
     
    <tr>
    	<td colspan="2"><table width="100%"><tr><td><hr></td></tr></table></td>
    
    </tr>
    <tr>
    	<td colspan="2"><table width="100%"><tr><td>
        <p><strong>Return Policy:</strong>&nbsp;&nbsp;At NET.A.KART we try to deliver perfectly every time. But on the off-chance if you need to return the item, please do so keeping the original Brand box/price tag, original packing and invoice intact, without which it will be difficult for us to act on your request. Terms and conditions apply.</p>
 <p>The good sold as part of this shipment are intended for end user consumption of retail sale and no for re-sale.</p></td></tr></table></td>
    <p><i>Return Address:</i>{{var surname}}, {{var saddress}}, {{var city}}, {{var state}}, {{var postalcode}}, {{var country}}</p>
    </tr>
</table> 

</body>   
