
<!--<div class="menu_order">
    <ul>
    <li><a href="http://www.netakart.com/index.php/salesreport/order">Dashboards</a></li>
    <li><a href="http://www.netakart.com/index.php/salesreport/margins">Sales & Margin</a></li>
    <li><a href="">COD Remit</a></li>
    <li><a href="">Payments to Vendor</a></li>
    <li><a href="">Vendor Performance</a></li>
    <li><a href="">Logistics Performance</a></li>
    </ul>
</div>-->


<div class="menu_order">
<ul id="example">
<li><div class="dash">&nbsp;</div><a href="http://www.netakart.com/index.php/salesreport/order">Dashboards</a></li>

<li><div class="sale">&nbsp;</div><a href="http://www.netakart.com/index.php/salesreport/margins/">Sales & Margin</a>
  <ul>
  <li><a href="http://www.netakart.com/index.php/salesreport/margins/?s=complete">Delivered</a></li>
  <li><a href="http://www.netakart.com/index.php/salesreport/margins/?s=returns">Returns</a></li>
  <li><a href="http://www.netakart.com/index.php/salesreport/margins/?s=canceled">Cancelled</a></li>
  <li><a href="http://www.netakart.com/index.php/salesreport/marketing">Marketing vs. Sales</a></li>
  <li><a href="http://www.netakart.com/index.php/salesreport/categorywise">Category-Wise Sale</a></li>
  <li><a href="http://www.netakart.com/index.php/salesreport/vendorwise">Vendor-Wise Stock</a></li>
  </ul>
</li>

<li> <div class="cod">&nbsp;</div><a href="http://www.netakart.com/index.php/salesreport/cod">COD Remit</a></li>
<li> <div class="pay">&nbsp;</div><a href="http://www.netakart.com/index.php/salesreport/vpayments">Payments to Vendor</a></li>
<li> <div class="ven">&nbsp;</div><a href="">Vendor Performance</a></li>
<li><div class="logi">&nbsp;</div><a href="">Logistics Performance</a></li>
</ul>
<script type="text/javascript">make_tree_menu('example');</script>
</div>