<?php
	$products = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect(array('sku','name','qty','supplier'))->load();
	$vendors =array();
	foreach($products as $product){
		$_item = $product->getId();
		$optionvalue = $product->getResource()->getAttributeRawValue($_item, 'supplier', Mage::app()->getStore());
		$supplierId = $product->getResource()->getAttribute('supplier')->getSource()->getOptionText($optionvalue);
		
		$vendors[$supplierId][] = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product)->getQty();
		/*if($product->getCategoryIds()){
			print_r($product->getCategoryIds());
		}*/	
		
	}
	
	echo $this->getChildHtml("order_list_toolbar"); ?>

<style>
#padd th{border-right:1px solid #000;}
.menu_font_style th{padding:10px;}
form th{ text-align:center;}
.supplier_order_list td{border-right:1px solid #000; border-bottom:1px solid #000; text-align:center;}
</style>

<div class="supllier_admin_content  supplier_admin_order_list">
<h1>
<?php
/*
	if($this->getRequest()->getParam('catId')){
		echo $this->getCategoryByName($this->getRequest()->getParam('catId'));
	}
	else{*/
		echo'Vendor-Wise Stock'; 
/*	}*/
	?>
</h1>
<!--
<div id="visualization" style="width: 98%; height: 400px; border:1px solid #ccc; float:left;"></div>
<!--<div id="chart_payment" style="width: 33%; height: 400px; border:1px solid #ccc; float:left;">&nbsp;</div>
<div id="chart_div" style="width: 33%; height: 400px; border:1px solid #ccc; float:left; margin:0px 10px;"></div>-->

<div style="clear:both;"></div>
<?php
			/*$catOrdersChart = array();
			 $i=0; foreach($orders as $orderChart){
		
			$catIdChart[] = $this->getCategoryName($orderChart['product_id'],$level);
			$pidChart[] = $orderChart['product_id'];
			
			}
			
			$catOrdersChart = $this->getCategoryByProduct($pidChart,$catIdChart);
			*/
			/*if(count($catOrdersChart > 0)){ ?>
				<script type="text/javascript" src="http://www.google.com/jsapi"></script>
			<script type="text/javascript">
                //load package
                google.load('visualization', '1', {packages: ['corechart']});
            </script>	
				<script type="text/javascript">
            function drawVisualization() {
                // Create and populate the data table.
                var data = google.visualization.arrayToDataTable([
                    ['PL', 'Ratings'],
                    <?php
                    foreach($catOrdersChart as $catOrderChart):
                        $name = $this->getCategoryByName($catOrderChart['category_id']);
						$ratings = round($catOrderChart['week1'],0);
                        echo "['{$name}', {$ratings}],";
                    endforeach;
                    ?>
                ]);
 				var options = {
						  title: 'Vendor-wise Stock %'
						  
        		};
                // Create and draw the visualization.
                new google.visualization.PieChart(document.getElementById('visualization')).
                draw(data, options);
            }
			
			
			/*function drawPaymentGraph() {
                // Create and populate the data table.
				<?php
				/*$cod = array();
				$prepaid = array();
				foreach($catOrdersChart as $catOrderPChart):
                  	$cod[] = $catOrderPChart['totalCOD'];		
					$prepaid[] = $catOrderPChart['totalPrePaid'];		  
                 endforeach;
				?>	
                var data = google.visualization.arrayToDataTable([
                    ['PL', 'Ratings', { role: 'style' }],
                    ['COD', <?php echo array_sum($cod);?>,'color: grey'],['Prepaid', <?php echo array_sum($prepaid);*/?><!--, 'color: #76A7FA'],
                ]);
 				var options = {
						  title: 'Payment Method'
						  
        		};
                // Create and draw the visualization.
                new google.visualization.PieChart(document.getElementById('chart_payment')).
                draw(data, options);
            }*/
			
			
			/*function drawChart () {
				-->
				<?php
					/*$del = array();	
					$pro = array();
					$hol = array();
					$ret = array();
					$can = array();
                    foreach($catOrdersChart as $catOrderChart):
                       $del[] = $catOrderChart['Complete'];
					   $pro[] = ($catOrderChart['Processing'] + $catOrderChart['Readyforpickup'] + $catOrderChart['Pending'] + $catOrderChart['HandedtoCourier']);
					   $hol[] = $catOrderChart['Hold'];
					   $ret[] = $catOrderChart['Returns'];
					   $can[] = $catOrderChart['Canceled'];
					  
                    endforeach;
					 $d = array_sum($del);
					$p = array_sum($pro);
					$h = array_sum($hol);
					$r = array_sum($ret);
					$c = array_sum($can);*/
                    ?>
					
			<!--	var data = google.visualization.arrayToDataTable([
					 ['Element', '', { role: 'style' }],
					 ['Delivered', <?php //echo $d;?>, 'green'],            // RGB value
					 ['Processing', <?php //echo $p;?>, 'silver'],            // English color name
					 ['Hold', <?php //echo $h;?>, 'grey'],            // English color name
					 ['Canceled', <?php //echo $c;?>, 'red'],
					 ['Returns', <?php //echo $r;?>, 'color: red' ], // CSS-style declaration
				  ]);

				
				var options = {
						  title: 'Order Status'
						  
        		};

				 new google.visualization.BarChart(document.getElementById('chart_div')).
                draw(data, options);
			}*/

            google.setOnLoadCallback(drawVisualization);
			google.setOnLoadCallback(drawChart);
			google.setOnLoadCallback(drawPaymentGraph);
        </script>
        -->
			<?php //}	
			?>

<form method="post" action="" name="frmPayment">
<table class="supplier_order_list st" style="width:100%; border:1px solid #000; margin-top:20px;">
	
	    <tr class="menu_font_style " id="padd">
                <th><?php echo $this->__('S. No.') ?></th>
                <th><?php echo $this->__('Supplier Name') ?></th>
                <th><?php echo $this->__('Total Products') ?></th>
	    </tr>
        <?php 
				$i = 1;
				foreach($vendors as $name => $total):
				
		?>
        <tr>
             <td><?php echo $i;?></td>
             <td><?php echo $name; ?></td>
             <td><?php echo array_sum($vendors[$name]);?></td>
         </tr>
         <?php  $i++; endforeach;?>
 </table> 
 </form>    
</div>
<?php echo $this->getChildHtml("order_list_toolbar"); ?>